---
- name: Configure VLANs
  hosts: switch
  gather_facts: false

  tasks:
    - name: Configure VLANs
      cisco.ios.ios_vlan:
        vlan_id: "{{ item.id }}"
        name: "{{ item.name }}"
        state: present
      loop:
        - { id: 10, name: 'VLAN10_STUD1' }
        - { id: 20, name: 'VLAN20' }

    - name: Save configuration
      cisco.ios.ios_config:
        save_when: modified
