---
- name: Configure Router Interfaces
  hosts: R1
  gather_facts: no
  connection: network_cli

  vars:
    # Interface configuration variables
    interface1_name: "GigabitEthernet0/0/0"
    interface1_ip: "192.168.12.2"
    interface1_subnet: "255.255.255.0"    

  tasks:
    - name: Configure interface {{ interface1_name }}
      ios_config:
        parents: "interface {{ interface1_name }}"
        lines:
          - ip address {{ interface1_ip }} {{ interface1_subnet }}
          - no shutdown

- name: Configure HSRP on Routers
  hosts: R1
  gather_facts: no

  tasks:
    - name: Configure interface Gig0/0/0 with HSRP
      cisco.ios.ios_config:
        lines:
          - interface GigabitEthernet0/0/0
          - ip address {{ item.ip }} 255.255.255.0
          - standby version 2
          - standby 1 ip 192.168.12.1
          - standby 1 priority "{{ item.priority }}"
          - standby 1 preempt
        parents: interface GigabitEthernet0/1
      loop:
        - { priority: 110 }

- name: Configure Routing between STUD1 and STUD2
  hosts: R1
  gather_facts: no

  tasks:
    - name: Enable OSPF routing
      cisco.ios.ios_ospf:
        ospf:
          processes:
            - process_id: 1
              networks:
                - address: 192.168.12.0
                  wildcard_bits: 0.0.0.255
                  area: 0
                  router id: 1.1.1.1

- name: Configure DHCP on Cisco Router
  hosts: routers
  gather_facts: false
  connection: network_cli

  vars:
    dhcp_pool_name: LAN_POOL
    dhcp_network: 192.168.10.0
    dhcp_netmask: 255.255.255.0
    dhcp_default_router: 192.168.10.1
    dhcp_dns_server: 8.8.8.8
    dhcp_lease_time: 7

  tasks:
    - name: Configure DHCP Pool
      ios_config:
        lines:
          - ip dhcp pool {{ dhcp_pool_name }}
          - network {{ dhcp_network }} {{ dhcp_netmask }}
          - default-router {{ dhcp_default_router }}
          - dns-server {{ dhcp_dns_server }}
          - lease {{ dhcp_lease_time }}

