---
- name: Configure VLANs on Switch
  hosts: SW1
  gather_facts: false
  connection: network_cli
  tasks:
    - name: Configure VLANs
      cisco.ios.ios_config:
        lines:
          - vlan 12
          - name VLAN12_STUD2
          - vlan 10
          - name VLAN10 mgmt
          - vlan 11
          - name VLAN11_STUD1
          - vlan 13
          - name VLAN13_mgmt2

- name: Configure switchports on Switch
  hosts: SW1
  gather_facts: false
  connection: network_cli
  tasks:
    - name: Set ports 1-3 to trunk mode
      cisco.ios.ios_config:
        parents: "interface range GigabitEthernet1/0/1-10"
        lines:
          - switchport mode trunk